### ISSUE TITLE
Error deploying .jar in webapp with Jenkinsfile

### ISSUE THREAD

**Issue by AlejandroGil** [jenkinsci/azure-app-service-plugin#34] opened 2018-06-28 16:52 UTC
Hello,

When I try to deploy a java .jar file into my webapp, the following error appears:

```
Starting Azure Web App Deployment
xxxxxxxx.jar is not WAR file. Will skip.
web.config is not WAR file. Will skip.
Done Azure Web App deployment.
 ``` 
Is there any way to deploy a .jar file?

Thank you!

**Comment by yungezz** [comment] 2018-07-17 02:39
close this since it's by design behavior. jar file deploy isn't support today yet. While we do have plan to support it in near future, maybe in next release. stay tuned.

**Closed by yungezz** 2018-07-17 02:39 UTC
